name: Deploy Portfolio

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install dependencies
      run: npm ci

    - name: Build project
      run: npm run build

    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Create backup of current deployment
          if [ -d /home/ubuntu/Portfolio ]; then
            cp -r /home/ubuntu/Portfolio /home/ubuntu/Portfolio_backup_$(date +%Y%m%d_%H%M%S)
          fi
          
          # Create directory if it doesn't exist
          mkdir -p /home/ubuntu/Portfolio

    - name: Copy files via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: "dist/*"
        target: "/home/ubuntu/Portfolio"
        strip_components: 1

    - name: Restart application
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /home/ubuntu/Portfolio
          
          # Install serve if not already installed
          if ! command -v serve &> /dev/null; then
            npm install -g serve
          fi
          
          # Delete existing PM2 process if exists
          pm2 delete portfolio || true
          
          # Start new PM2 process
          pm2 start "serve -s . -l 3000" --name portfolio
          
          # Save PM2 configuration
          pm2 save
          
          # Setup PM2 startup script
          pm2 startup systemd -u ubuntu --hp /home/ubuntu || true

    - name: Health check
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Wait for service to start
          sleep 5
          
          # Check if service is running
          if pm2 status portfolio | grep -q "online"; then
            echo "✅ Deployment successful! Portfolio is running."
          else
            echo "❌ Deployment failed! Portfolio is not running."
            pm2 logs portfolio --lines 20
            exit 1
          fi
